repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-json
      name: Check JSON files
      exclude: ^\.vscode/
    - id: check-yaml
      name: Check YAML files
    - id: check-toml
      name: Check TOML files
    - id: end-of-file-fixer
      name: Ensure proper file endings
    - id: trailing-whitespace
      name: Remove unnecessary whitespace from code
      args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.7
  hooks:
    - id: ruff
      name: Lint Python code with ruff
      types_or: [python, pyi, jupyter]
      args: [--fix]
    - id: ruff-format
      name: Format Python code with ruff
      types_or: [python, pyi, jupyter]

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.2
  hooks:
    - id: poetry-check
      name: Check poetry config
    - id: poetry-lock
      name: Lock Python dependencies

- repo: local
  hooks:
    - id: nbconvert
      name: Strip output of Jupyter notebooks
      stages: [commit]
      entry: jupyter nbconvert
      args: [--clear-output, --inplace]
      language: system
      files: \.ipynb$
