name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]
        steps:
            - name: Check out source code
              uses: actions/checkout@v4

            - name: Install poetry
              run: pipx install poetry

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "poetry"

            - name: Install dependencies
              run: poetry install --with dev

            - name: Run linters
              env:
                SKIP: poetry-lock
              run: poetry run pre-commit run --all-files

            - name: Run tests
              run: poetry run pytest
